blueprint:
  name: Turn Light ON and OFF
  description: Turn light on when motion is detected, and turn it off when motion is not detected.
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      description: Choose the motion sensor to control the lights.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    target_light:
      name: Target Light
      description: Choose the lights that you want to control.
      selector:
        target:
          entity:
            domain: light
    delay_time:
      name: Number of seconds 
      description: Number of seconds, after which the lights will turn off.
      selector:
        number:
          min: 0
          max: 3600
          step: 1
          unit_of_measurement: "seconds"

trigger:
  - platform: state
    entity_id: !input motion_sensor
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: !input motion_sensor
    from: 'on'
    to: 'off'
    for:
      minutes: !input delay_time
condition: []
action:
  - choose:
    - conditions: "{{ trigger.to_state.state == 'on' }}"
      sequence:
      - service: light.turn_on
        data:
          brightness_pct: 75
        target: !input target_light
    default:
      - service: light.turn_off
        data: {}
        target: !input target_light
mode: single
